---

#### Defensive Programming

#### Set Facts
- name: Set JBoss EAP Download Facts
  set_fact:
    jboss_eap_library_dest: "/opt/{{ jboss_eap_user }}"
  tags:
    - jboss

- name: Set JBoss EAP Group Facts
  set_fact:
    jboss_eap_group: "{{ jboss_eap_user }}"
  tags:
    - jboss

##
# The version compare allows to decide what version of EAP that is provisioned and
# use the appropriate init.d scripts and init.d configuraitons
# In EAP6 its jboss-as-[standalone|domain].sh and jboss-as.conf respectively
# In EAP7 its jboss-eap-rhel.sh and jboss-eap.conf respectively
##
- name: Set JBoss EAP Service Directories Facts
  set_fact:
    jboss_eap_home: "{{ jboss_eap_library_dest }}/jboss-as-7.1.1.Final"
    jboss_eap_service_conf_dir: "/etc/jboss-as/"
    jboss_eap_service_log_dir: "/var/log/{{ jboss_eap_user }}"
    jboss_eap_service_data_dir: "/var/run/{{ jboss_eap_user }}"
  tags:
    - jboss

- name: Set JBoss EAP Service Files Facts
  set_fact:
    jboss_eap_service_conf_file: "{{ jboss_eap_service_conf_dir }}/jboss-as.conf"
    jboss_eap_bin_dir: "{{ jboss_eap_home }}/bin"
    jboss_eap_runtime_conf_file: "{{ jboss_eap_home }}/bin/standalone.conf"
    jboss_eap_service_file: jboss-as-standalone.sh  #"{{ (jboss_eap_base_version | version_compare('7.0','<')) | ternary('jboss-as-'+jboss_eap_mode+'.sh','jboss-eap-rhel.sh')}}"
  tags:
    - jboss

##
# RHEL 6 expects init.d service with extension
##
- name: Set JBoss EAP Service Name EL 6
  set_fact:
    jboss_eap_service_name: "{{jboss_eap_service_file}}"
  when: (ansible_distribution_major_version | version_compare('6','<='))
  tags:
    - jboss

##
# RHEL 7 expects init.d service without extension
##
- name: Set JBoss EAP Service Name EL 7
  set_fact:
    jboss_eap_service_name: "{{jboss_eap_service_file | splitext | first }}"
  when: (ansible_distribution_major_version | version_compare('7','>='))
  tags:
    - jboss

- debug: msg="EAP HOME {{ jboss_eap_home }} and Service file {{jboss_eap_service_file}}  Service Name {{jboss_eap_service_name}}"

#### Create Service Account

- include: jboss_service.yml

#### Defensive Programming To Check If EAP Is Already Installed

- name: Check Existence of Libraries
  become: true
  stat:
    path: "{{ jboss_eap_library_dest + '/jboss-eap-6.4/version.txt'}}"
  register: jboss_eap_exists
  tags:
    - jboss

########################################

- name: Extract JBoss EAP Libraries
  #become: true
  unarchive:
    src: "jboss-as-7.1.1.Final.tar.gz"
#    src: "http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.tar.gz"
#    src: "http://10.40.86.106/APP/WAS/jboss-as-7.1.1.Final.tar.gz"
    dest: "{{ jboss_eap_library_dest }}"
    creates: jboss-eap-7.1.1
#    copy: no
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
  tags:
    - jboss
  when: jboss_eap_exists.stat.exists == false


## Copy jboss-as-{{jboss_eap_mode}}.sh or jboss-eap-rhel.sh file to /etc/init.d
- name: Copy JBoss EAP Service File
  become: true
  copy:
    src: "{{jboss_eap_bin_dir}}/init.d/{{jboss_eap_service_file}}"
    dest: /etc/init.d
    remote_src: True
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
    mode: "755"
  notify:
    - Restart jboss-as Service
    - Verify jboss-as is running
  tags:
    - jboss

- name: Add jboss-as Service
  become: true
  command: "chkconfig --add {{jboss_eap_service_file}}"
  tags:
    - jboss

- name: Enable jboss-as Service
  become: true
  service:
    name: "{{jboss_eap_service_file}}"
    enabled: yes
  tags:
    - jboss

#### Set Sensible Defaults For Runtime

- name: Set Web Bind Address
  lineinfile:
    dest: "{{ jboss_eap_runtime_conf_file }}"
    line: JAVA_OPTS="$JAVA_OPTS -Djboss.bind.address={{jboss_eap_bind_web_address}}"
  when: jboss_eap_bind_web_interface
  tags:
    - jboss

- name: Set Management Bind Address
  lineinfile:
    dest: "{{ jboss_eap_runtime_conf_file }}"
    line: JAVA_OPTS="$JAVA_OPTS -Djboss.bind.address.management={{jboss_eap_bind_management_address}}"
  when: jboss_eap_bind_management_interface
  tags:
    - jboss

- name: Set User Time Zone for Logs
  lineinfile:
    dest: "{{ jboss_eap_runtime_conf_file }}"
    line: "JAVA_OPTS=\"$JAVA_OPTS -Duser.timezone={{jboss_eap_logging_timezone}}\""
  tags:
    - jboss

- name: create postgresql datasource directory
  file:
    path: /opt/jboss-as/jboss-as-7.1.1.Final/modules/org/postgresql/main
    state: directory
    owner: jboss-as
    group: jboss-as
    recurse: yes
  tags:
    - jboss

# Replace with RPM Installation postgresql94-jdbc
#- name: copy postgresql jdbc driver
#  copy:
#    src: postgresql-9.4-1206-jdbc41.jar
#    dest: /opt/jboss-as/jboss-as-7.1.1.Final/modules/org/postgresql/main/postgresql-9.4-1206-jdbc41.jar
#    owner: jboss-as
#    group: jboss-as
#  tags:
#    - jboss

# Replace with RPM Installation postgresql-jdbc
- name: copy postgresql jdbc driver
  copy:
    src: postgresql-42.0.0.jre7.jar
    dest: /opt/jboss-as/jboss-as-7.1.1.Final/modules/org/postgresql/main/postgresql-42.0.0.jre7.jar
    owner: jboss-as
    group: jboss-as
  tags:
    - jboss

- name: copy postgresql jdbc driver
  template:
    src: module.xml
    dest: /opt/jboss-as/jboss-as-7.1.1.Final/modules/org/postgresql/main/module.xml
    owner: jboss-as
    group: jboss-as
  tags:
    - jboss

- name: copy standalone.xml 
  template:
    src: standalone.xml.j2
    dest: /opt/jboss-as/jboss-as-7.1.1.Final/standalone/configuration/standalone.xml
    owner: jboss-as
    group: jboss-as
    backup: yes
  ignore_errors: true
  tags:
    - jboss

- name: create ROOT.war
  file:
    path: /opt/jboss-as/jboss-as-7.1.1.Final/standalone/deployments/ROOT.war
    state: directory
    owner: jboss-as
    group: jboss-as
    recurse: yes
  tags:
    - jboss

- name: copy index.jsp
  template:
    src: index.jsp
    dest: /opt/jboss-as/jboss-as-7.1.1.Final/standalone/deployments/ROOT.war/
    owner: jboss-as
    group: jboss-as
  tags:
    - jboss

- name: add hostname in hosts
  lineinfile: 
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }}   {{ansible_hostname}} {{ ansible_hostname }}.localdomain"
  tags:
    - jboss

- name: restart jboss
  service:
    name: jboss-as-standalone
    state: restarted
  tags:
    - jboss
