---
- name: SKT playbook - Waiting for the target-node to be rebooted
  hosts: test01
  gather_facts: no
  tasks:
  - name: Pause for 50 seconds
    pause:
      seconds: 50
  - name: Waiting for the target-node to be off
  #  local_action: wait_for host=192.168.253.249 port=22 state=stopped delay=3 timeout=300
    local_action: shell ansible -i /selee/T-auto/hosts -m ping test01
    register: result
    until: result.rc != 0
    retries: 720 
    delay: 5
    ignore_errors: yes
  - name: Waiting for the target-node to be on
    local_action: wait_for host=192.168.253.249 port=22 state=started delay=3 timeout=300
...
