---
##
# Refer to JBoss EAP documentation
# https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.4/html/Installation_Guide/sect-Service_Configuration.html#Install_JBoss_Enterprise_Application_Platform_6_Red_Hat_Enterprise_Linux_Service
# https://access.redhat.com/documentation/en/red-hat-jboss-enterprise-application-platform/7.0.beta/installation-guide/chapter-4-configuring-jboss-eap-to-run-as-a-service
##


- name: Create JBoss EAP Group
  group:
    name: "{{ jboss_eap_group }}"
    system: yes
    state: present
    gid: "400"

- name: Create JBoss EAP User
  user:
    name: "{{ jboss_eap_user }}"
    comment: "JBoss EAP User"
    uid: "400"
    group: "{{ jboss_eap_group }}"
    home: "{{ jboss_eap_library_dest }}"
    shell: "/bin/bash"

- name: copy profile
  template:
    src: bash_profile.j2
    dest: "~{{ jboss_eap_user }}/.bash_profile"
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"

- name: edit user limit nofile
  pam_limits:
    domain: "{{ jboss_eap_user }}" 
    limit_type: "-"
    limit_item: nofile
    value: 65535

- name: edit user limit nproc
  pam_limits:
    domain: "{{ jboss_eap_user }}" 
    limit_type: "-"
    limit_item: nproc
    value: 65535

- name: Create JBoss EAP Library Destination
  become: true
  file:
    path: "{{ jboss_eap_library_dest }}"
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
    state: directory
    mode: "755"

- name: Create JBoss EAP Service Conf Directory
  file:
    path: "{{ jboss_eap_service_conf_dir }}"
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
    state: directory
    mode: "755"

- name: Copy JBoss EAP Service Conf File
  template:
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
    src: jboss-as.conf.j2
    dest: "{{ jboss_eap_service_conf_file }}"
    backup: yes
    mode: "755"

- name: Create JBoss EAP Service Log Directory
  file:
    path: "{{ jboss_eap_service_log_dir }}"
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
    state: directory
    mode: "755"

- name: Create JBoss EAP Service Runtime Data Directory
  file:
    path: "{{ jboss_eap_service_data_dir }}"
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
    state: directory
    mode: "755"
