---
- hosts: "{{host_to_run}}"
  vars:
  - host_name: "{{ ansible_hostname }}"
  tasks:
  - name: selinux disable
    selinux:  
      state: disabled

  - name:  delete rhgs host from host file
    lineinfile:
      dest: /etc/hosts
      regexp: 'rhgs'
      line: ""

  - name:  delete reposerver host from host file
    lineinfile:
      dest: /etc/hosts
      regexp: 'reposerver'
      line: ""

  - name: delete repo file
    file:  
      path: /etc/yum.repos.d/rhel7-gluster.repo
      state: absent

  - name: stop httpd service
    service:
      name: httpd
      state: stopped
    ignore_errors: yes

  - name: yum delete httpd
    yum:  
      name: httpd 
      state: absent
