- name: Launch web instances
  os_server:
    auth: "{{ os_auth }}"
    name: "{{ webspec.name }}{{ item }}"
    flavor: "{{ webspec.flavor }}"
    image: "{{ webspec.image }}"
    key_name: "{{ webspec.key_name }}"
    state: present
    wait: true
    nics:
      - net-name: "{{ webspec.netname }}"
    meta: "hostname={{ webname }}"
    security_groups: "{{ webspec.secgroup }}"
    floating_ip_pools: "{{ webspec.floatingippools }}"
#    auto_ip: no
    reuse_ips: false
    timeout: 500
  register: web_hosts
  until: web_hosts.server.public_v4 is defined
#  until: "{{ web_hosts.server.public_v4 }} != ''"
  retries: 5
  delay: 10
#  ignore_errors: true
  with_sequence: 
    count={{ webcount }}

- name: add hosts to inventory
  add_host: 
    name: "{{ item.server.name }}"
    groups: webgroup
    ansible_ssh_host: "{{ item.server.public_v4 }}"
    private_ip: "{{ item.server.private_v4 }}"
  with_items: "{{ web_hosts.results }}"
  changed_when: false

- name: create volume
  os_volume:
    auth: "{{ os_auth }}"
    state: present
    size: "{{webvolsize }}"
    display_name: "{{ item.server.name }}-vol"
  with_items: "{{ web_hosts.results }}"

- name: attach volume to server
  os_server_volume:
    auth: "{{ os_auth }}"
    state: present
    server: "{{ item.server.name }}"
    volume: "{{ item.server.name }}-vol"
    device: "{{ device_path }}"
  with_items: "{{ web_hosts.results }}"
