- name: check vg exist
  shell: >
    vgs | grep vg_app | wc -l
  register: vg_app_exist

- name: create vg
  lvg:
    vg: vg_app 
    pvs: /dev/vdb
  when: ( vg_app_exist == 0 )

- name: create dbbase lvol
  lvol:
    vg: vg_app
    lv: lv_pgdb
    size: "{{ (((((dbvolsize|int)*1024)*0.24)|round|int)-4) }}m" 
  when: ( vg_app_exist == 0 )

- name: create db data lvol
  lvol:
    vg: vg_app
    lv: lv_pgdata
    #size: 14g
    size: "{{ (((((dbvolsize|int)*1024)*0.74)|round|int)-4) }}m" 
  when: ( vg_app_exist == 0 )

- name: format pgdb filesystem
  filesystem:
    fstype: xfs 
    dev: /dev/vg_app/lv_pgdb
  when: ( vg_app_exist == 0 )

- name: format pgdata filesystem
  filesystem:
    fstype: xfs 
    dev: /dev/vg_app/lv_pgdata
  when: ( vg_app_exist == 0 )

- name: mount pgdb filesystem
  mount:
    name: "{{ dbbase }}"
    src: /dev/vg_app/lv_pgdb
    fstype: xfs
    state: mounted
  when: ( vg_app_exist == 0 )

- name: mount pgdata filesystem
  mount:
    name: "{{ dbdir }}"
    src: /dev/vg_app/lv_pgdata
    fstype: xfs
    state: mounted
  when: ( vg_app_exist == 0 )
