- name: create vg
  lvg:
    vg: vg_app 
    pvs: /dev/vdb
  tags:
    - ppas

- name: create dbbase lvol
  lvol:
    vg: vg_app
    lv: lv_pgdb
    size: "{{ (((((dbvolsize|int)*1024)*0.24)|round|int)-4) }}m" 
  tags:
    - ppas

- name: create db data lvol
  lvol:
    vg: vg_app
    lv: lv_pgdata
    #size: 14g
    size: "{{ (((((dbvolsize|int)*1024)*0.74)|round|int)-4) }}m" 
  tags:
    - ppas

- name: format pgdb filesystem
  filesystem:
    fstype: xfs 
    dev: /dev/vg_app/lv_pgdb
  tags:
    - ppas

- name: format pgdata filesystem
  filesystem:
    fstype: xfs 
    dev: /dev/vg_app/lv_pgdata
  tags:
    - ppas

- name: mount pgdb filesystem
  mount:
    name: "{{ dbbase }}"
    src: /dev/vg_app/lv_pgdb
    fstype: xfs
    state: mounted
  tags:
    - ppas

- name: mount pgdata filesystem
  mount:
    name: "{{ dbdir }}"
    src: /dev/vg_app/lv_pgdata
    fstype: xfs
    state: mounted
  tags:
    - ppas
