---
- name: Set up Vars
  include_vars: main.yml

- name: Create a server instance on AWS
  ec2:
#    aws_access_key: "{{ ansible_aws_access_key }}"
#    aws_secret_key: "{{ ansible_aws_secret_key }}"
#    aws_region: "{{ ansible_aws_region }}"
    key_name: ansible-poc-doosan
#    key_name: id_rsa
    group: "{{ security_name }}"
#    instance_type: t2.micro
    instance_type: t2.medium
# TOKYO
    image: ami-6b0d5f0d
# SEOUL
#    image: ami-3eee4150
# TOKYO
    region: ap-northeast-1
# SEOUL
#    region: ap-northeast-2a
#    image: ami-6b0d5f0d
#    image: ami-efaf0181
    wait: yes
    instance_tags:
      prov: ansible
      Name: "tower-{{ instance_name }}"
      Group: "tower-{{ instance_group_name }}"
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 8
        delete_on_termination: true
# TOKYO
    vpc_subnet_id: subnet-08f08353
# SEOUL
#    vpc_subnet_id: subnet-fce3d894
#    vpc_subnet_id: subnet-d383dbbb
    assign_public_ip: yes
    count_tag:
      Name: "tower-{{ instance_name }}"
      Group: "tower-{{ instance_group_name }}"
    exact_count: 1
  register: ec2
    
- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_dns_name }}"
    groupname: "{{ instance_group_name }}"
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 100
    connect_timeout: 100
    state: started
    search_regex: OpenSSH
  with_items: "{{ ec2.instances }}"
